env:
  browser: true
  es2021: true
extends: "eslint-config-discourse"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: "off"
  no-restricted-globals: "off"
  "@babel/plugin-syntax-import-attributes/deprecatedAssertSyntax": "off"