env:
  browser: true
  es2021: true
extends: "eslint-config-discourse"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: "off"
  no-restricted-globals: "off"